services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - ~/.dotfiles/bash/bashrc:/home/opam/.bashrc
      - ~/.dotfiles/bash/bash_profile:/home/opam/.bash_profile
      - ~/.dotfiles/git/gitconfig:/home/opam/.gitconfig
      - ~/.dotfiles/nvim:/home/opam/.config/nvim
      - ~/.dotfiles/starship/starship.toml:/home/opam/.config/starship.toml
      - ~/.dotfiles/yazi:/home/opam/.config/yazi
    working_dir: /home/opam/workspace/
